apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: apacheds
  name: apacheds
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apacheds
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/archnav-cloudification-default: "true"
        io.kompose.service: apacheds
    spec:
      containers:
        - image: djolo2211/archnav_cloudification-apacheds:1.0
          name: apacheds
          ports:
            - containerPort: 10389
              hostPort: 10389
              protocol: TCP
      restartPolicy: Always
